version: '3'

services:
  mypostgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  mygoapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mypostgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "user=myuser password=mypassword dbname=mydatabase sslmode=disable"
